version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jmendezpod/backend:8.0.0

  frontend:
    build: ./frontend
    image: jmendezpod/frontend:8.0.0