apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: taskmanager
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}