apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskbackend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: taskbackend
  template:
    metadata:
      labels:
        backend: taskbackend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:{{ .Values.mysql.service.port }}/{{ .Values.mysql.database }}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.mysql.username | quote }}
        - name: SPRING_DATASOURCE_PASSWORD
          value: {{ .Values.mysql.password | quote }}
        ports:
        - containerPort: 8080
        resources:
{{ toYaml .Values.backend.resources | indent 10 }}