apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql-root-password: {{ randAlphaNum 16 | b64enc | quote }}
  mysql-username: {{ .Values.mysql.username | b64enc | quote }}
  mysql-password: {{ randAlphaNum 16 | b64enc | quote }}
  mysql-database: {{ .Values.mysql.database | b64enc | quote }}