apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  custom.cnf: |
    [mysqld]
    default-authentication-plugin=mysql_native_password
    max_connections={{ .Values.mysql.config.maxConnections }} 