apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  user-password: {{ .Values.mysql.password | b64enc | quote }}