# MySQL configuration
mysql:
  image:
    repository: mysql
    tag: 8.0.41
    pullPolicy: IfNotPresent
  config:
    maxConnections: 200
  rootPassword: root123
  database: taskmanager
  username: taskuser
  password: task123
  storageSize: 10Gi
  service:
    port: 3306
    type: ClusterIP

# Application configuration
app:
  image:
    repository: jmendezpod/taskmanager-app
    tag: 1.7
    pullPolicy: IfNotPresent
  service:
    port: 80
    targetPort: 8080
    type: LoadBalancer
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi