# This file contains the default values for the TaskManager Helm chart.
   
# Default values for taskmanager-chart.
namespace: ""

# MySQL configuration
mysql:
  image:
    repository: mysql
    tag: 8.0.41
    pullPolicy: IfNotPresent
  config:
    maxConnections: 200
  database: taskmanager
  username: taskuser
  storageSize: 10Gi
  service:
    port: 3306
    type: ClusterIP

# Backend configuration
backend:
  image:
    repository: jmendezpod/backend
    tag: latest
    imagePullPolicy: Always
  service:
    port: 80
    targetPort: 8080
    type: ClusterIP
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi